DROP DATABASE CheeversBrown_PE11;

CREATE DATABASE CheeversBrown_PE11;

USE CheeversBrown_PE11;

CREATE TABLE PERSON (
    PersonID INT NOT NULL AUTO_INCREMENT,
    FirstName VARCHAR(25) NOT NULL,
    LastName VARCHAR(25) NOT NULL,
    PRIMARY KEY (PersonID)
) ENGINE=InnoDB;

CREATE TABLE PATIENT (
    PatientID INT NOT NULL,
    DoctorID INT NOT NULL,
    FOREIGN KEY (PatientID) REFERENCES PERSON(PersonID),
    PRIMARY KEY (PatientID)
) ENGINE=InnoDB;

CREATE TABLE STAFF (
    StaffID INT NOT NULL,
    ManagerID INT NOT NULL,
    FOREIGN KEY (StaffID) REFERENCES PERSON(PersonID),
    PRIMARY KEY (StaffID)
) ENGINE=InnoDB;

ALTER TABLE STAFF ADD CONSTRAINT FK_ManagerID FOREIGN KEY (ManagerID) REFERENCES STAFF(StaffID);

CREATE TABLE DOCTOR (
    DoctorID INT NOT NULL,
    MentorID INT NOT NULL,
    FOREIGN KEY (DoctorID) REFERENCES STAFF(StaffID),
    PRIMARY KEY (DoctorID)
) ENGINE=InnoDB;

ALTER TABLE PATIENT ADD CONSTRAINT FK_Patient_Doctor FOREIGN KEY (DoctorID) REFERENCES DOCTOR(DoctorID);
ALTER TABLE DOCTOR ADD CONSTRAINT FK_Doctor_Mentor FOREIGN KEY (MentorID) REFERENCES DOCTOR(DoctorID);

CREATE TABLE NURSE (
    NurseID INT NOT NULL,
    Certification ENUM('lpn', 'rn', 'aprn') NOT NULL,
    FOREIGN KEY (NurseID) REFERENCES STAFF(StaffID),
    PRIMARY KEY (NurseID)
) ENGINE=InnoDB;

CREATE TABLE SUPPORT_STAFF (
    SupportStaffID INT NOT NULL,
    Wage DECIMAL(4,2) NOT NULL,
    FOREIGN KEY (SupportStaffID) REFERENCES STAFF(StaffID),
    PRIMARY KEY (SupportStaffID)
) ENGINE=InnoDB;

CREATE TABLE DEPARTMENT (
    DepartmentID INT NOT NULL,
    DepartmentName VARCHAR(50) NOT NULL,
    PRIMARY KEY (DepartmentID)
) ENGINE=InnoDB;

CREATE TABLE DEPARTMENT_STAFF (
    DepartmentID INT NOT NULL,
    StaffID INT NOT NULL,
    FOREIGN KEY (DepartmentID) REFERENCES DEPARTMENT(DepartmentID),
    FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID),
    PRIMARY KEY (DepartmentID, StaffID)
) ENGINE=InnoDB;

CREATE TABLE INSURANCE_COMPANY (
    coID INT NOT NULL AUTO_INCREMENT,
    coName VARCHAR(80) NOT NULL,
    PRIMARY KEY (coID)
) ENGINE=InnoDB;

CREATE TABLE INSURANCE_POLICY (
    PolicyNum VARCHAR(25) NOT NULL,
    PatientID INT NOT NULL,
    InsCoID INT NOT NULL,
    PRIMARY KEY (PolicyNum)
) ENGINE=InnoDB;

ALTER TABLE INSURANCE_POLICY ADD CONSTRAINT FK_PatientID FOREIGN KEY (PatientID) REFERENCES PATIENT(PatientID);
ALTER TABLE INSURANCE_POLICY ADD CONSTRAINT FK_InsCoID FOREIGN KEY (InsCoID) REFERENCES INSURANCE_COMPANY(coID);

SHOW TABLES;